# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_encoder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_encoder.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x15message_encoder.proto\x12\x0crbk.protocol\"/\n\x0fMessage_Encoder\x12\r\n\x05\x65ncID\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE_ENCODER = _descriptor.Descriptor(
  name='Message_Encoder',
  full_name='rbk.protocol.Message_Encoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encID', full_name='rbk.protocol.Message_Encoder.encID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='rbk.protocol.Message_Encoder.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Message_Encoder'] = _MESSAGE_ENCODER

Message_Encoder = _reflection.GeneratedProtocolMessageType('Message_Encoder', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_ENCODER,
  __module__ = 'message_encoder_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Encoder)
  ))
_sym_db.RegisterMessage(Message_Encoder)


# @@protoc_insertion_point(module_scope)
