/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Aug 31 19:34:14 2018. */

#include "message_battery.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Battery_fields[7] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Battery, percetage, percetage, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Battery, charge_current, percetage, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Battery, charge_voltage, charge_current, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Battery, is_charging, charge_voltage, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Battery, temperature, is_charging, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Battery, cycle, temperature, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
