/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Dec 22 13:55:00 2017. */

#ifndef PB_RBK_PROTOCOL_MESSAGE_RFID_PB_H_INCLUDED
#define PB_RBK_PROTOCOL_MESSAGE_RFID_PB_H_INCLUDED
#include <pb.h>

#include "message_header.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _rbk_protocol_Message_RFIDNode {
    uint32_t id;
    uint32_t count;
    rbk_protocol_Message_Header header;
    uint32_t strength;
/* @@protoc_insertion_point(struct:rbk_protocol_Message_RFIDNode) */
} rbk_protocol_Message_RFIDNode;

typedef struct _rbk_protocol_Message_RFID {
    pb_size_t rfid_nodes_count;
    rbk_protocol_Message_RFIDNode rfid_nodes[1];
/* @@protoc_insertion_point(struct:rbk_protocol_Message_RFID) */
} rbk_protocol_Message_RFID;

/* Default values for struct fields */

/* Initializer values for message structs */
#define rbk_protocol_Message_RFIDNode_init_default {0, 0, rbk_protocol_Message_Header_init_default, 0}
#define rbk_protocol_Message_RFID_init_default   {0, {rbk_protocol_Message_RFIDNode_init_default}}
#define rbk_protocol_Message_RFIDNode_init_zero  {0, 0, rbk_protocol_Message_Header_init_zero, 0}
#define rbk_protocol_Message_RFID_init_zero      {0, {rbk_protocol_Message_RFIDNode_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define rbk_protocol_Message_RFIDNode_id_tag     1
#define rbk_protocol_Message_RFIDNode_count_tag  2
#define rbk_protocol_Message_RFIDNode_header_tag 3
#define rbk_protocol_Message_RFIDNode_strength_tag 4
#define rbk_protocol_Message_RFID_rfid_nodes_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t rbk_protocol_Message_RFIDNode_fields[5];
extern const pb_field_t rbk_protocol_Message_RFID_fields[2];

/* Maximum encoded size of messages (where known) */
#define rbk_protocol_Message_RFIDNode_size       42
#define rbk_protocol_Message_RFID_size           44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGE_RFID_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
