/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Dec 15 22:47:54 2017. */

#include "message_ultrasonic.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_UltraNode_fields[13] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_UltraNode, id, id, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, dist, id, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, valid, dist, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, pos_x, valid, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, pos_y, pos_x, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, pos_angle, pos_y, 0),
    PB_FIELD(  7, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, max_dist, pos_angle, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, min_dist, max_dist, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, aperture, min_dist, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, forbidden, aperture, 0),
    PB_FIELD( 11, MESSAGE , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, header, forbidden, &rbk_protocol_Message_Header_fields),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_UltraNode, offset_time_ms, header, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_Ultrasonic_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Ultrasonic, cycle, cycle, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, rbk_protocol_Message_Ultrasonic, nodes, cycle, &rbk_protocol_Message_UltraNode_fields),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ultrasonic, base_time_ns, nodes, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_UltraNode, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_rbk_protocol_Message_UltraNode_rbk_protocol_Message_Ultrasonic)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_UltraNode, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_rbk_protocol_Message_UltraNode_rbk_protocol_Message_Ultrasonic)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
