/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Mar 04 15:03:26 2018. */

#include "message_pgv.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_PGV_DMT_fields[10] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_PGV_DMT, tag_diff_x, tag_diff_x, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, tag_diff_y, tag_diff_x, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, tag_diff_angle, tag_diff_y, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, tag_value, tag_diff_angle, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, warning_code, tag_value, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, device_address, warning_code, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, is_DMT_detected, device_address, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, is_error, is_DMT_detected, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_PGV_DMT, is_absolute_X_pos_valid, is_error, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
