/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Jun 13 20:31:18 2017. */

#include "message_header.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Header_fields[3] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Header, pub_nsec, pub_nsec, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Header, data_nsec, pub_nsec, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
