/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Oct 26 10:10:37 2017. */

#include "message_ekf_position.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Ekf_Position_fields[13] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Ekf_Position, header, header, &rbk_protocol_Message_Header_fields),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, x, header, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, y, x, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, angle, y, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, steer_angle, angle, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, vel_x, steer_angle, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, vel_y, vel_x, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, vel_rotate, vel_y, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, odom_x, vel_rotate, 0),
    PB_FIELD( 10, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, odom_y, odom_x, 0),
    PB_FIELD( 11, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, odom_angle, odom_y, 0),
    PB_FIELD( 12, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Ekf_Position, imu_yaw, odom_angle, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_Ekf_Position, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_rbk_protocol_Message_Ekf_Position)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_Ekf_Position, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_rbk_protocol_Message_Ekf_Position)
#endif


/* @@protoc_insertion_point(eof) */
