/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sat Aug 05 15:55:57 2017. */

#include "message_ipconfig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_ipconfig_fields[6] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_ipconfig, ip, ip, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ipconfig, subnet_mask, ip, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ipconfig, gateway, subnet_mask, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ipconfig, mac_addr, gateway, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ipconfig, save_to_flash, mac_addr, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
