/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Dec 18 20:59:43 2018. */

#include "message_fork.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Fork_fields[10] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Fork, height, height, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, incline, height, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, fork_val, incline, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, incline_val, fork_val, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, fork_error, incline_val, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, height_in_place, fork_error, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, incline_in_place, height_in_place, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, get_goods, incline_in_place, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork, auto_flag, get_goods, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_Fork_Downward_fields[16] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Fork_Downward, type, type, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, pump, type, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, encodeline, pump, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, pressureSensor, encodeline, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, minHeight, pressureSensor, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, maxHeight, minHeight, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, CAN_ID, maxHeight, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, max_angle, CAN_ID, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, min_angle, max_angle, 0),
    PB_FIELD( 10, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, driverPeriod, min_angle, 0),
    PB_FIELD( 11, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, upBuffer, driverPeriod, 0),
    PB_FIELD( 12, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, downBuffer, upBuffer, 0),
    PB_FIELD( 13, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, leftSteerRange, downBuffer, 0),
    PB_FIELD( 14, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, rightSteerRange, leftSteerRange, 0),
    PB_FIELD( 15, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Fork_Downward, steeroffset, rightSteerRange, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
