/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 13 19:07:53 2017. */

#include "message_encoder.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Encoder_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Encoder, encID, encID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Encoder, value, encID, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
