/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Jan 03 17:44:28 2019. */

#include "message_liftret.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Lift_Ret_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Lift_Ret, retAction, retAction, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Ret, toLimitFini, retAction, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Ret, spinDegreeFini, toLimitFini, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
