/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Jan 10 11:18:05 2018. */

#include "message_named_io.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Named_DI_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Named_DI, header, header, &rbk_protocol_Message_Header_fields),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Named_DI, name, header, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Named_DI, num, name, 0),
    PB_FIELD(  4, BOOL    , REPEATED, STATIC  , OTHER, rbk_protocol_Message_Named_DI, id, num, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_Named_DO_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Named_DO, header, header, &rbk_protocol_Message_Header_fields),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Named_DO, name, header, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Named_DO, num, name, 0),
    PB_FIELD(  4, BOOL    , REPEATED, STATIC  , OTHER, rbk_protocol_Message_Named_DO, id, num, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_Named_DI, header) < 65536 && pb_membersize(rbk_protocol_Message_Named_DO, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_rbk_protocol_Message_Named_DI_rbk_protocol_Message_Named_DO)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_Named_DI, header) < 256 && pb_membersize(rbk_protocol_Message_Named_DO, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_rbk_protocol_Message_Named_DI_rbk_protocol_Message_Named_DO)
#endif


/* @@protoc_insertion_point(eof) */
