/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Jan 03 17:46:20 2019. */

#include "message_navigation.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_NavStatus_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavStatus, blocked, blocked, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavSpeed_fields[7] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavSpeed, x, x, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavSpeed, y, x, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavSpeed, rotate, y, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavSpeed, header, rotate, &rbk_protocol_Message_Header_fields),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavSpeed, steer_angle, header, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavSpeed, spin_speed, steer_angle, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_ManualSpeed_fields[5] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_ManualSpeed, x, x, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ManualSpeed, y, x, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ManualSpeed, rotate, y, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_ManualSpeed, steer_angle, rotate, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavPose_fields[4] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavPose, x, x, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavPose, y, x, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavPose, angle, y, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavTopoPose_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavTopoPose, id, id, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavTopoPose, angle, id, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavState_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavState, pose, pose, &rbk_protocol_Message_NavPose_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavState, speed, pose, &rbk_protocol_Message_NavSpeed_fields),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavState, radius, speed, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavPath_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, rbk_protocol_Message_NavPath, states, states, &rbk_protocol_Message_NavState_fields),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavPath, find_path, states, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavTarget_fields[6] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavTarget, x, x, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavTarget, y, x, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavTarget, angle, y, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavTarget, run_mode, angle, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavTarget, topo_target_id, run_mode, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_NavInfo_fields[11] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_NavInfo, nav_mode, nav_mode, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_cmd, nav_mode, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_target_x, nav_cmd, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_target_y, nav_target_x, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_target_theta, nav_target_y, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_target_mode, nav_target_theta, 0),
    PB_FIELD(  7, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_speed_x, nav_target_mode, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_speed_y, nav_speed_x, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, nav_speed_w, nav_speed_y, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_NavInfo, topo_target_id, nav_speed_w, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_NavSpeed, header) < 65536 && pb_membersize(rbk_protocol_Message_NavState, pose) < 65536 && pb_membersize(rbk_protocol_Message_NavState, speed) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_rbk_protocol_Message_NavStatus_rbk_protocol_Message_NavSpeed_rbk_protocol_Message_ManualSpeed_rbk_protocol_Message_NavPose_rbk_protocol_Message_NavTopoPose_rbk_protocol_Message_NavState_rbk_protocol_Message_NavPath_rbk_protocol_Message_NavTarget_rbk_protocol_Message_NavInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_NavSpeed, header) < 256 && pb_membersize(rbk_protocol_Message_NavState, pose) < 256 && pb_membersize(rbk_protocol_Message_NavState, speed) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_rbk_protocol_Message_NavStatus_rbk_protocol_Message_NavSpeed_rbk_protocol_Message_ManualSpeed_rbk_protocol_Message_NavPose_rbk_protocol_Message_NavTopoPose_rbk_protocol_Message_NavState_rbk_protocol_Message_NavPath_rbk_protocol_Message_NavTarget_rbk_protocol_Message_NavInfo)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
