/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sat Jan 05 15:21:33 2019. */

#include "message_liftconfig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Lift_Elevation_fields[18] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Lift_Elevation, ID, ID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, driverBrand, ID, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, Inverse, driverBrand, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, haveEncoder, Inverse, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, encoderWithMotor, haveEncoder, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, encoderLines, encoderWithMotor, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, mmCntRatio, encoderLines, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, limitType, mmCntRatio, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, toplimit, limitType, 0),
    PB_FIELD( 10, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, bottomlimit, toplimit, 0),
    PB_FIELD( 11, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, topDIHighTrigger, bottomlimit, 0),
    PB_FIELD( 12, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, bottomDIHighTrigger, topDIHighTrigger, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, safeControlType, bottomDIHighTrigger, 0),
    PB_FIELD( 14, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, timeLimit, safeControlType, 0),
    PB_FIELD( 15, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, setSpeedPriority, timeLimit, 0),
    PB_FIELD( 16, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, setToLimitPriority, setSpeedPriority, 0),
    PB_FIELD( 17, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Elevation, heightLimit, setToLimitPriority, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_Lift_Rotation_fields[17] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Lift_Rotation, ID, ID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, driverBrand, ID, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, Inverse, driverBrand, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, haveEncoder, Inverse, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, encoderWithMotor, haveEncoder, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, encoderLines, encoderWithMotor, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, degreeRatio, encoderLines, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, setSpeedPriority, degreeRatio, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, spinDegreePriority, setSpeedPriority, 0),
    PB_FIELD( 10, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, spinDegreeSpeed, spinDegreePriority, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, spinDegreeFollowPriority, spinDegreeSpeed, 0),
    PB_FIELD( 12, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, spinDegreeFollowWithZero, spinDegreeFollowPriority, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, zeroPointDI, spinDegreeFollowWithZero, 0),
    PB_FIELD( 14, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, DIHighTrigger, zeroPointDI, 0),
    PB_FIELD( 15, FLOAT   , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, spinFollowZeroInitSpeed, DIHighTrigger, 0),
    PB_FIELD( 16, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Lift_Rotation, spinDegreeWithZero, spinFollowZeroInitSpeed, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
