/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed Jan 10 11:18:05 2018. */

#ifndef PB_RBK_PROTOCOL_MESSAGE_NAMED_IO_PB_H_INCLUDED
#define PB_RBK_PROTOCOL_MESSAGE_NAMED_IO_PB_H_INCLUDED
#include <pb.h>

#include "message_header.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _rbk_protocol_Message_Named_DI {
    rbk_protocol_Message_Header header;
    char name[50];
    uint32_t num;
    pb_size_t id_count;
    bool id[16];
/* @@protoc_insertion_point(struct:rbk_protocol_Message_Named_DI) */
} rbk_protocol_Message_Named_DI;

typedef struct _rbk_protocol_Message_Named_DO {
    rbk_protocol_Message_Header header;
    char name[50];
    uint32_t num;
    pb_size_t id_count;
    bool id[16];
/* @@protoc_insertion_point(struct:rbk_protocol_Message_Named_DO) */
} rbk_protocol_Message_Named_DO;

/* Default values for struct fields */

/* Initializer values for message structs */
#define rbk_protocol_Message_Named_DI_init_default {rbk_protocol_Message_Header_init_default, "", 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define rbk_protocol_Message_Named_DO_init_default {rbk_protocol_Message_Header_init_default, "", 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define rbk_protocol_Message_Named_DI_init_zero  {rbk_protocol_Message_Header_init_zero, "", 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define rbk_protocol_Message_Named_DO_init_zero  {rbk_protocol_Message_Header_init_zero, "", 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define rbk_protocol_Message_Named_DI_header_tag 1
#define rbk_protocol_Message_Named_DI_name_tag   2
#define rbk_protocol_Message_Named_DI_num_tag    3
#define rbk_protocol_Message_Named_DI_id_tag     4
#define rbk_protocol_Message_Named_DO_header_tag 1
#define rbk_protocol_Message_Named_DO_name_tag   2
#define rbk_protocol_Message_Named_DO_num_tag    3
#define rbk_protocol_Message_Named_DO_id_tag     4

/* Struct field encoding specification for nanopb */
extern const pb_field_t rbk_protocol_Message_Named_DI_fields[5];
extern const pb_field_t rbk_protocol_Message_Named_DO_fields[5];

/* Maximum encoded size of messages (where known) */
#define rbk_protocol_Message_Named_DI_size       114
#define rbk_protocol_Message_Named_DO_size       114

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGE_NAMED_IO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
