/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Oct 23 18:50:32 2017. */

#ifndef PB_RBK_PROTOCOL_MESSAGE_MAGNETIC_PB_H_INCLUDED
#define PB_RBK_PROTOCOL_MESSAGE_MAGNETIC_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _rbk_protocol_Message_MagneticNode {
    uint32_t id;
    bool backward;
    pb_size_t value_count;
    bool value[16];
/* @@protoc_insertion_point(struct:rbk_protocol_Message_MagneticNode) */
} rbk_protocol_Message_MagneticNode;

typedef struct _rbk_protocol_Message_Magnetic {
    pb_size_t magnetic_nodes_count;
    rbk_protocol_Message_MagneticNode magnetic_nodes[2];
/* @@protoc_insertion_point(struct:rbk_protocol_Message_Magnetic) */
} rbk_protocol_Message_Magnetic;

/* Default values for struct fields */

/* Initializer values for message structs */
#define rbk_protocol_Message_MagneticNode_init_default {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define rbk_protocol_Message_Magnetic_init_default {0, {rbk_protocol_Message_MagneticNode_init_default, rbk_protocol_Message_MagneticNode_init_default}}
#define rbk_protocol_Message_MagneticNode_init_zero {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define rbk_protocol_Message_Magnetic_init_zero  {0, {rbk_protocol_Message_MagneticNode_init_zero, rbk_protocol_Message_MagneticNode_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define rbk_protocol_Message_MagneticNode_id_tag 1
#define rbk_protocol_Message_MagneticNode_backward_tag 2
#define rbk_protocol_Message_MagneticNode_value_tag 3
#define rbk_protocol_Message_Magnetic_magnetic_nodes_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t rbk_protocol_Message_MagneticNode_fields[4];
extern const pb_field_t rbk_protocol_Message_Magnetic_fields[2];

/* Maximum encoded size of messages (where known) */
#define rbk_protocol_Message_MagneticNode_size   40
#define rbk_protocol_Message_Magnetic_size       84

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGE_MAGNETIC_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
