/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Jan 03 17:45:26 2019. */

#include "message_odometer.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Odometer_fields[13] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Odometer, header, header, &rbk_protocol_Message_Header_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, cycle, header, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, x, cycle, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, y, x, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, angle, y, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, is_stop, angle, 0),
    PB_FIELD(  7, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, vel_x, is_stop, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, vel_y, vel_x, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, vel_rotate, vel_y, 0),
    PB_FIELD( 10, INT32   , REPEATED, STATIC  , OTHER, rbk_protocol_Message_Odometer, encoder, vel_rotate, 0),
    PB_FIELD( 11, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, steer_angle, encoder, 0),
    PB_FIELD( 12, DOUBLE  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Odometer, spin_angle, steer_angle, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_Odometer, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_rbk_protocol_Message_Odometer)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(rbk_protocol_Message_Odometer, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_rbk_protocol_Message_Odometer)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
