/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Nov 13 14:00:50 2018. */

#include "message_dmx512.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_Dmx512_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Dmx512, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Dmx512, battery, type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Dmx512, color_r, battery, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Dmx512, color_g, color_r, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Dmx512, color_b, color_g, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, rbk_protocol_Message_Dmx512, color_w, color_b, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
