/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Aug 10 16:50:58 2018. */

#include "message_io.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rbk_protocol_Message_DI_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_DI, num, num, 0),
    PB_FIELD(  2, BOOL    , REPEATED, STATIC  , OTHER, rbk_protocol_Message_DI, id, num, 0),
    PB_FIELD(  3, BOOL    , REPEATED, CALLBACK, OTHER, rbk_protocol_Message_DI, forbidden, id, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_DO_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_DO, num, num, 0),
    PB_FIELD(  2, BOOL    , REPEATED, STATIC  , OTHER, rbk_protocol_Message_DO, id, num, 0),
    PB_LAST_FIELD
};

const pb_field_t rbk_protocol_Message_Astern_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, rbk_protocol_Message_Astern, status, status, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
