/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Jun 09 10:40:18 2017. */

#include "QueryCan.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t QueryCan_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, QueryCan, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, QueryCan, num, type, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
