#ifndef _CHASSIS_CMD_TYPE_H_
#define _CHASSIS_CMD_TYPE_H_

enum motorDriverCmdType{
	DRV_CMD_NULL,
	DRV_CMD_ACTURAL_POS,
	DRV_CMD_ACTURAL_SPEED,
	DRV_CMD_TARGET_SPEED,
	DRV_CMD_DRI_STATE,
	DRV_CMD_INIT_CMD,
	DRV_CMD_UNDEFINED,
};


#endif
