# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanFrame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CanFrame.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x43\x61nFrame.proto\"\x8a\x01\n\x08\x43\x61nFrame\x12\n\n\x02ID\x18\x01 \x01(\r\x12\x10\n\x08\x45xtended\x18\x02 \x01(\x08\x12\x0e\n\x06Remote\x18\x03 \x01(\x08\x12\x0b\n\x03\x44LC\x18\x04 \x01(\r\x12\x0c\n\x04\x44\x61ta\x18\x05 \x01(\x0c\x12\x0f\n\x07\x43hannel\x18\x06 \x01(\r\x12\x11\n\tTimestamp\x18\x07 \x01(\r\x12\x11\n\tDirection\x18\x08 \x01(\x08*\x1b\n\tDIRE_ENUM\x12\x06\n\x02RX\x10\x00\x12\x06\n\x02TX\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DIRE_ENUM = _descriptor.EnumDescriptor(
  name='DIRE_ENUM',
  full_name='DIRE_ENUM',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TX', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=159,
  serialized_end=186,
)
_sym_db.RegisterEnumDescriptor(_DIRE_ENUM)

DIRE_ENUM = enum_type_wrapper.EnumTypeWrapper(_DIRE_ENUM)
RX = 0
TX = 1



_CANFRAME = _descriptor.Descriptor(
  name='CanFrame',
  full_name='CanFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='CanFrame.ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Extended', full_name='CanFrame.Extended', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Remote', full_name='CanFrame.Remote', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DLC', full_name='CanFrame.DLC', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='CanFrame.Data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Channel', full_name='CanFrame.Channel', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='CanFrame.Timestamp', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Direction', full_name='CanFrame.Direction', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['CanFrame'] = _CANFRAME
DESCRIPTOR.enum_types_by_name['DIRE_ENUM'] = _DIRE_ENUM

CanFrame = _reflection.GeneratedProtocolMessageType('CanFrame', (_message.Message,), dict(
  DESCRIPTOR = _CANFRAME,
  __module__ = 'CanFrame_pb2'
  # @@protoc_insertion_point(class_scope:CanFrame)
  ))
_sym_db.RegisterMessage(CanFrame)


# @@protoc_insertion_point(module_scope)
