# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_ipconfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_ipconfig.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x16message_ipconfig.proto\x12\x0crbk.protocol\"m\n\x10Message_ipconfig\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x13\n\x0bsubnet_mask\x18\x02 \x01(\x0c\x12\x0f\n\x07gateway\x18\x03 \x01(\x0c\x12\x10\n\x08mac_addr\x18\x04 \x01(\x0c\x12\x15\n\rsave_to_flash\x18\x05 \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE_IPCONFIG = _descriptor.Descriptor(
  name='Message_ipconfig',
  full_name='rbk.protocol.Message_ipconfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='rbk.protocol.Message_ipconfig.ip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subnet_mask', full_name='rbk.protocol.Message_ipconfig.subnet_mask', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateway', full_name='rbk.protocol.Message_ipconfig.gateway', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac_addr', full_name='rbk.protocol.Message_ipconfig.mac_addr', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_to_flash', full_name='rbk.protocol.Message_ipconfig.save_to_flash', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['Message_ipconfig'] = _MESSAGE_IPCONFIG

Message_ipconfig = _reflection.GeneratedProtocolMessageType('Message_ipconfig', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_IPCONFIG,
  __module__ = 'message_ipconfig_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_ipconfig)
  ))
_sym_db.RegisterMessage(Message_ipconfig)


# @@protoc_insertion_point(module_scope)
