# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryCan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryCan.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eQueryCan.proto\"%\n\x08QueryCan\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0b\n\x03num\x18\x02 \x01(\r*\x17\n\nQUERY_TYPE\x12\t\n\x05\x46RAME\x10\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_QUERY_TYPE = _descriptor.EnumDescriptor(
  name='QUERY_TYPE',
  full_name='QUERY_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FRAME', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=57,
  serialized_end=80,
)
_sym_db.RegisterEnumDescriptor(_QUERY_TYPE)

QUERY_TYPE = enum_type_wrapper.EnumTypeWrapper(_QUERY_TYPE)
FRAME = 0



_QUERYCAN = _descriptor.Descriptor(
  name='QueryCan',
  full_name='QueryCan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='QueryCan.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='QueryCan.num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['QueryCan'] = _QUERYCAN
DESCRIPTOR.enum_types_by_name['QUERY_TYPE'] = _QUERY_TYPE

QueryCan = _reflection.GeneratedProtocolMessageType('QueryCan', (_message.Message,), dict(
  DESCRIPTOR = _QUERYCAN,
  __module__ = 'QueryCan_pb2'
  # @@protoc_insertion_point(class_scope:QueryCan)
  ))
_sym_db.RegisterMessage(QueryCan)


# @@protoc_insertion_point(module_scope)
