#define CONFIG_HEARTS_LEDS_PRIORITY 2

#define CONFIG_DIO_PRIORITY 3
#define CONFIG_GYRO_PRIORITY 4
#define CONFIG_CHASSIS_PRIORITY 5
#define CONFIG_COMMAND_DISPATCH_PRIORITY 6
#define CONFIG_CONFIG_PRIORITY 7
